#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
  CREATE ROLE $SONAR_USER WITH LOGIN PASSWORD '$SONAR_PASSWORD';
  CREATE DATABASE $SONAR_DB;
  GRANT ALL PRIVILEGES ON DATABASE $SONAR_DB TO $SONAR_USER;
EOSQL
